// 机房详情
export let pcRoomJson = {
  aqSbcount: '安全设备数量',
  sysCompanyCode: '所属公司',
  jfWz: '机房位置',
  areaName: '省直部门',
  constructionCost: '建设费用',
  jgTrje: '机柜投入金额(万元)',
  uspTrje: 'UPS投入金额(万元)',
  ywDept: '运维单位',
  fwWz: '服务位置',
  rjCuont: '软件数量',
  operationCost: '运维费用',
  jfNm: '机房名称',
  wlsbTrje: '网络设备投入金额(万元)',
  updateName: '录入人员',
  opSystem: '操作系统',
  ccSbcount: '存储设备数量',
  sfYfw: '是否采用云服务',
  fwqTrje: '服务器投入金额',
  ktCount: '空调投入金额(万元)',
  name: '部门名称',
  createName: '创建人',
  bpmStatus: '流程状态',
  updateDate: '更新日期',
  zysbTrje: '专用设备投入金额(万元)',
  wtDeptname: '委托单位名称',
  updateBy: '更新人员名称',
  ywTrje: '每年的运维费用(万元)',
  ndlCount: '机房年用电量总数（度）',
  sfJf: '是否有机房',
  fwqCount: '服务器数量',
  rjzTrje: '软件总投入金额(万元)',
  wlSbcount: '网络设备投入金额(万元)',
  createDate: '机房创建日期',
  ktTrje: '空调投入金额',
  aqsbTrje: '安全设备投入金额(万元)',
  yjCount: '硬件数量',
  ccsbTrje: '存储设备投入金额(万元)',
  yjzTrje: '硬件总投入金额',
  yfwType: '云服务类型',
  createBy: '创建人登录名称',
  upsCount: 'ups数量',
  zySbcount: '专用设备数量',
  jfCount: '机柜数量',
  jfSize: '机房面积'
}
export let pcRoomFormat = {
  fwWz: o => ['本基信息中心机房', '其他'][o-1],
  opSystem: o => ['windows', 'linux', '', '其他'][0-1],
  sfYfw: o => ['是', '否'][o - 1],
  bpmStatus: o => ['待提交', '已提交', '已驳回', '已审核通过'][o-1],
  yfwType: o => ['私有云', '公有云','', '其他'][o-1],
  
}