export let businessJson = {
    sysStatus:'系统建设状态',
    sysNm:'信息系统名称',
    bearerNetwork:'承载网络',
    useDate:'系统开始使用日期',
    sfUse:'是否在用',
    bearerNetwork_desc:'承载网络描述',
    unitNm:'部门单位名称',
    mtcUnit:'系统运行维护单位',
    mtcLinkway:'系统运维单位联系人电话',
    storeSize:'数据存储大小(GB)',
    optMode:'部署方式',
    chargeDept:'主管部门处室',
    chargeLinkman:'主管部门处室联系人',
    chargePhone:'主管部门处室负责人电话',
    rangeUse:'系统用户范围',
    apprDept:'项目立项审批部门',
    manageUnit:'系统建设单位',
    charger:'系统建设单位负责人',
    chargeLinkway:'系统建设单位负责人联系方式',
    createUnit:'系统承建单位',
    createrLinkway:'系统承建单位联系人方式',
    funingSource:'项目建设金额来源',
    createStartDate:"系统建设起始时间",
    safeLev:'安全等级定级情况',
    freqUse:'系统年度使用频率',
    deplSite:'系统部署地点',
    bulidTrje:'系统建设费用',
    totalMtExp:'截至2016年运维费用总支出(万元)',
    protCondition:'信息系统分级保护定级情况',
    userScale:'系统用户规模',
    mtcFeeSource:'运维费来源',
    sfQyun:'迁云状况',
    qyunTime:'已迁云或计划迁云时间',
    exchange:'接入省级数据共享交换平台情况',
    sfIntegration:'是否整合',
    integrationNm:'整合系统名称',
    mxgzSyfw:'面向公众使用范围',
    sfJrswsbsdt:'接入省网上办事大厅情况',
    sysFb:"系统分布情况",
    szbsTrje:'市州部署投入资金(万元)',
    ryTrqk:'人员投入情况(人)',
    sjaqYq:'数据安全要求',
    nbSyfw:'内部使用范围',
    qtSyfw:'其他使用范围',
    sfQgtz:'是否全国统建',
    jfwz:'机房',
    qxbsTrje:'区(县)部署投入资金(万元)',
    ysBm:'验收部门',
    xmYsqk:'验收情况',
    szbsTrje:'市州部署投入资金(万元)',
    sysDesc:'主要功能',
    wwwIpAddress:'互联网域名或IP地址',
    outIpAddress:'电子政务外网域名或IP地址',
}
export let businessFormat = {
  bearerNetwork:v=>['政务外网','互联网','其他专网'][v-1],
  sfUse:v=>['是','否'][v-1],
  optMode:v=>['公有云平台','私有云平台','-','传统方式'][v-1],
  sysStatus:v =>['拟建','在建','已建','国家派发','省级派发','上级派发'][v-1],
  bearer_network:v=>['政务外网','互联网','其他专网'][v-1],
  sfUse:v=>['是','否','试用中'][v-1],
  funingSource:v=>['财政拨款','自筹','BT项目','其他'][v-1],
  safeLev:v=>['一级','二级','三级','四级','五级','未定级'][v-1],
  protCondition:v=>['未定秘','秘密','机密','绝密'][v-1],
  mtcFeeSource:v=>['财政拨款','自筹','BT项目','其他'][v-1],
  sfQyun:v=>['已迁云','计划迁云','不迁云'][v-1],
  exchange:v=>['是','否'][v-1],
  sfIntegration:v=>['是','否'][v-1],
  mxgzSyfw:v=>['内部公众','组织公众','非组织公众'][v-1],
  sfJrswsbsdt:v=>['是','否','试用中'][v-1] ,
  sysFb:v=>['省级部署' ,'市州部署' ,'区(县)部署'][v-1],
  sjaqYq:v=>['涉密','敏感','不宜公开','依申请公开','可公开'][v-1],
  nbSyfw:v=>['省级使用', '市级使用','', '县级使用'][v-1],
  sfQgtz:v=>['是' ,'否' ,'试用中'][v-1],

}