export let association = {
  'beijing': 'geometryProvince/11',
  'tianjin': 'geometryProvince/12',
  'hebei': 'geometryProvince/13',
  'taiyuan': 'geometryProvince/14',
  'neimenggu': 'geometryProvince/15',
  'liaoning': 'geometryProvince/21',
  'jilin': 'geometryProvince/22',
  'heilongjiang': 'geometryProvince/23',
  'shanghai': 'geometryProvince/31',
  'jiangsu': 'geometryProvince/32',
  'zhejiang': 'geometryProvince/33',
  'anhui': 'geometryProvince/34',
  'fujian': 'geometryProvince/35',
  'jiangxi': 'geometryProvince/36',
  'shandong': 'geometryProvince/37',
  'henan': 'geometryProvince/41',
  'hubei': 'geometryProvince/42',
  'hunan': 'geometryProvince/43',
  'guangdong': 'geometryProvince/44',
  'guangxi': 'geometryProvince/45',
  'hainan': 'geometryProvince/46',
  'chongqing': 'geometryProvince/50',
  'sichuan': 'geometryProvince/51',
  'guizhou': 'geometryProvince/52',
  'yunnan': 'geometryProvince/53',
  'xizang': 'geometryProvince/54',
  'shanxi_': 'geometryProvince/61',
  'gansu': 'geometryProvince/62',
  'qinghai': 'geometryProvince/63',
  'ningxia': 'geometryProvince/64',
  'xinjiang': 'geometryProvince/65',
  'taiwan': 'geometryProvince/71',
  'xianggang': 'geometryProvince/81',
  'aomen': 'geometryProvince/82',
}
export let cityId = {
  '省直部门': 1,
  '贵阳市': 2,
  '遵义市': 3,
  '安顺市': 4,
  '黔南州': 5,
  '黔东南州': 6,
  '铜仁市': 7,
  '毕节市': 8,
  '六盘水市': 9,
  '黔西南州': 10
}